# Generated by Django 2.1.7 on 2019-03-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('x5', models.FloatField()),
                ('estimate', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
