# Generated by Django 2.1.7 on 2019-04-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Embarked', models.IntegerField()),
                ('Fare', models.FloatField()),
                ('Pclass', models.IntegerField()),
                ('Sex', models.IntegerField()),
                ('Family_Size', models.IntegerField()),
                ('Title2', models.IntegerField()),
                ('Ticket_info', models.IntegerField()),
                ('Cabin', models.IntegerField()),
                ('survive', models.IntegerField()),
            ],
            options={
                'ordering': ['Age'],
            },
        ),
    ]
