# Generated by Django 2.1.4 on 2018-12-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['address', 'time'],
            },
        ),
    ]
